spring:
  datasource:
    url: jdbc:mysql://39.96.36.251:3306/data?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: data
    password: 123456

server:
  port: 8088

mybatis:
  type-aliases-package: com.it.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
